(ns server.modules.rule.rule
	(:require [server.db :as db]
			  [server.utils :as utils]))

(defn- coll-name [houseId] (str "rules_" houseId))

(defn new-rules [obj houseId agentId]
	"Insert rules into database. These rules are those defined in the App, so are already accepted by the user."
	(if-let [rules (:rules obj)]
		(if (every? true? (map #(and (contains? % :nodeId) (contains? % :commandId) (contains? % :controllerId)  (contains? % :value) (contains? % :clauses)) rules))
				(if (every? true? 
					(map  #(db/insert? (coll-name houseId) (assoc % :accepted true :agentId agentId)) rules))
					{:status 200}
					{:status 500 :errorMessage "DB did not insert values."}
				)
				{:status 400 :errorMessage "Define nodeId, controllerId, commandId, value and clauses."}
		)
		{:status 400 :errorMessage "Rules not defined"}
	)
)

(defn get-rules [_ houseId controllerId]
	"Select rules from db that were generated and already accepted."
	(db/select (coll-name houseId) {:controllerId controllerId :accepted true}))

(defn get-learnt-rules [_ houseId controllerId]
	"Select rules from db that were generated by the machine learning algorithms."
	(db/select (coll-name houseId) {:controllerId controllerId :accepted false}))

(defn notify-learnt-rules[token msg]
	"Send a notification to user's device with new learnt rules."
	(utils/send-notification token msg))